#ifndef TCPNETWORKING_GLOBAL_H
#define TCPNETWORKING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPNETWORKING_LIBRARY)
#define TCPNETWORKING_EXPORT Q_DECL_EXPORT
#else
#define TCPNETWORKING_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPNETWORKING_GLOBAL_H
